[project]
name = "text2sql-wizard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.11.2",
]

[tool.ruff]
lint.select = ["E"]

# Never enforce `E501` (line length violations).
lint.ignore = ["E501"]
